name: CI workflow

on: pull_request 

jobs:
  ci:
    runs-on: windows-2022
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Intall
        run: npm ci

      - name: Tests
        run: npm test

    


